// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAM_r7Rfv7mLB-m1kkkp7NK8-XG3H6f4I',
    appId: '1:1095171762056:android:12c89521012eda1d4b7c3d',
    messagingSenderId: '1095171762056',
    projectId: 'social-event-guest-app',
    storageBucket: 'social-event-guest-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHeqRMZYukMGHnzt90rl13M7ypOD6_usg',
    appId: '1:1095171762056:ios:e0d8d6f0e2f3640a4b7c3d',
    messagingSenderId: '1095171762056',
    projectId: 'social-event-guest-app',
    storageBucket: 'social-event-guest-app.firebasestorage.app',
    iosBundleId: 'com.example.guestApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk2xEAzA51X2SVDaeYLH_rE2xUf1jK5xU',
    appId: '1:1095171762056:web:d55061341617e2404b7c3d',
    messagingSenderId: '1095171762056',
    projectId: 'social-event-guest-app',
    authDomain: 'social-event-guest-app.firebaseapp.com',
    storageBucket: 'social-event-guest-app.firebasestorage.app',
  );

}